export const WEBSITE_BASE_URL = 'http://localhost:5000'
export const PRODUCTS_BASEURL = 'http://localhost:5000/products'
export const ORDERS_BASEURL = 'http://localhost:5000/orders'
export const SHIPPING_BASEURL = 'http://localhost:5000/shipping'
export const NOTIFICATIONS_BASEURL = 'http://localhost:5000/notifications'
export const PAYMENTS_BASEURL = 'http://localhost:5000/payments'
export const USER_BASEURL = 'http://localhost:5000/me'